# Generated by Django 6.0.6 on 2026-06-04 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('cars', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='OEM-номер')),
                ('manufacturer_code', models.CharField(blank=True, max_length=100, verbose_name='Код производителя')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='Характеристики')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('quantity', models.IntegerField(default=0, verbose_name='Остаток на складе')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('orders_count', models.IntegerField(default=0, verbose_name='Продажи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand', verbose_name='Бренд')),
                ('cars', models.ManyToManyField(blank=True, related_name='products', to='cars.car', verbose_name='Совместимые автомобили')),
                ('categories', models.ManyToManyField(related_name='products', to='categories.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
