# Generated by Django 6.0.6 on 2026-06-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('generation', models.CharField(blank=True, max_length=100, verbose_name='Поколение')),
                ('year_from', models.IntegerField(blank=True, null=True, verbose_name='Год от')),
                ('year_to', models.IntegerField(blank=True, null=True, verbose_name='Год до')),
                ('engine', models.CharField(blank=True, max_length=100, verbose_name='Двигатель')),
                ('body_type', models.CharField(blank=True, max_length=50, verbose_name='Тип кузова')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['make', 'model', 'year_from'],
            },
        ),
    ]
