# Generated by Django 4.2.11 on 2026-04-22 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('generation', models.CharField(blank=True, max_length=100, verbose_name='Поколение')),
                ('year_from', models.IntegerField(blank=True, null=True, verbose_name='Год от')),
                ('year_to', models.IntegerField(blank=True, null=True, verbose_name='Год до')),
                ('engine', models.CharField(blank=True, max_length=100, verbose_name='Двигатель')),
                ('body_type', models.CharField(blank=True, max_length=50, verbose_name='Тип кузова')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand', verbose_name='Бренд')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cars', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['brand__name', 'model', 'year_from'],
            },
        ),
    ]
