# Generated by Django 6.0.5 on 2026-05-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('brand', 'model', 'generation', 'year_from')},
        ),
    ]
